name: CI with Summary

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          apt install make cmake g++ libaio-dev libgoogle-perftools-dev
          apt install libboost-all-dev
          apt install clang-format
          apt install libmkl-full-dev
      
      - name: Build project
        run: |
          cmake -S . -B build -DBUILD_PYTHON_BINDINGS=ON -Dpybind11_DIR=$(python -m pybind11 --cmakedir)
          cd build
          make -j
          cp bindings/*.so ../muvera_project/muvera_pybind
          cd ../muvera_project/
          pip install .

      - name: Run tests
        id: ctest
        run: |
          cd build && ctest
        continue-on-error: true
      
      - name: Run Python tests
        id: pytest
        run: |
          python bindings/tests/pybind_test.py
        continue-on-error: true

      - name: Record workflow result
        run: |
          if grep -q "failed" result.log; then
            echo "status=failed" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi
